### ISSUE TITLE
adding   -  window.open

### ISSUE THREAD

**Issue by condigital** [neutralinojs/proposals#3]
appreciate the great effort you have put into this project.

I would like to know if it is possible to implement the window.open function to open a window in the same process.

being part of the same process
both windows could communicate with each other and share cookies and other resources.
in this way both windows can communicate with each other, father and child

```
win=window.open("","pop", "width=640,height=360,scrollbars=no,menubar=no,toolbar=no,status=no");
win.document.body.style="background-color:#335060;color:#FFF";
win.document.body.innerHTML="<h1>Testing</h1>";

```

Thank You,  you are great.

**Comment by danidre14** [comment]
The window.open option already works as you would use it in your general browser.
If you mean opening multiple neu windows, then check `window.create` in the neu docs.

**Comment by condigital** [comment]
> The window.open option already works as you would use it in your general browser. If you mean opening multiple neu windows, then check `window.create` in the neu docs.

Sorry But  window.open is not working..  i have done many test
